/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daph_client;

/**
 *
 * @author DELL
 */
public class daph_AppMain extends javax.swing.JFrame {

    /**
     * Creates new form daph_AppMain
     */
    public daph_AppMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_u_md5 = new javax.swing.JTextField();
        txt_u_sha = new javax.swing.JTextField();
        txt_u_sha256 = new javax.swing.JTextField();
        txt_u_sha512 = new javax.swing.JTextField();
        txt_p_md5 = new javax.swing.JTextField();
        txt_p_sha = new javax.swing.JTextField();
        txt_p_sha256 = new javax.swing.JTextField();
        txt_p_sha512 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        originalPassword = new javax.swing.JLabel();
        originalUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Now, the encrypted user and password in the different methods:\n\n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 16, 18, 39);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("MD5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("SHA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("SHA256");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("SHA512");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("MD5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 17);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("SHA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("SHA256");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel9.setText("SHA512");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(jLabel9, gridBagConstraints);

        txt_u_md5.setPreferredSize(new java.awt.Dimension(500, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(txt_u_md5, gridBagConstraints);

        txt_u_sha.setPreferredSize(new java.awt.Dimension(500, 22));
        txt_u_sha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_u_shaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(txt_u_sha, gridBagConstraints);

        txt_u_sha256.setPreferredSize(new java.awt.Dimension(500, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(txt_u_sha256, gridBagConstraints);

        txt_u_sha512.setPreferredSize(new java.awt.Dimension(500, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(txt_u_sha512, gridBagConstraints);

        txt_p_md5.setPreferredSize(new java.awt.Dimension(500, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 17);
        jPanel1.add(txt_p_md5, gridBagConstraints);

        txt_p_sha.setPreferredSize(new java.awt.Dimension(500, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(txt_p_sha, gridBagConstraints);

        txt_p_sha256.setPreferredSize(new java.awt.Dimension(500, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(txt_p_sha256, gridBagConstraints);

        txt_p_sha512.setPreferredSize(new java.awt.Dimension(500, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 17);
        jPanel1.add(txt_p_sha512, gridBagConstraints);

        jLabel10.setText("User:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 33);
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 33);
        jPanel1.add(jLabel11, gridBagConstraints);

        originalPassword.setForeground(new java.awt.Color(153, 153, 153));
        originalPassword.setText("password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 0);
        jPanel1.add(originalPassword, gridBagConstraints);
        originalPassword.getAccessibleContext().setAccessibleName("originalPassword");

        originalUser.setForeground(new java.awt.Color(153, 153, 153));
        originalUser.setText("user");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        jPanel1.add(originalUser, gridBagConstraints);
        originalUser.getAccessibleContext().setAccessibleName("originalUser");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_u_shaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_u_shaActionPerformed
        // TODO add your handling ode here:
    }//GEN-LAST:event_txt_u_shaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daph_AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daph_AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daph_AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daph_AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }
    
    public void setArguments(String originalUsr, String originalPass,String usrMD5, String usrSHA, String usrSHA256, String usrSHA512,String pssMD5, String pssSHA, String pssSHA256, String pssSHA512){
        this.originalUser.setText(originalUsr);
        this.originalPassword.setText(originalPass);
        this.txt_u_md5.setText(usrMD5);
        this.txt_u_sha.setText(usrSHA);
        this.txt_u_sha256.setText(usrSHA256);
        this.txt_u_sha512.setText(usrSHA512);
        
        this.txt_p_md5.setText(pssMD5);
        this.txt_p_sha.setText(pssSHA);
        this.txt_p_sha256.setText(pssSHA256);
        this.txt_p_sha512.setText(pssSHA512);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel originalPassword;
    private javax.swing.JLabel originalUser;
    private javax.swing.JTextField txt_p_md5;
    private javax.swing.JTextField txt_p_sha;
    private javax.swing.JTextField txt_p_sha256;
    private javax.swing.JTextField txt_p_sha512;
    private javax.swing.JTextField txt_u_md5;
    private javax.swing.JTextField txt_u_sha;
    private javax.swing.JTextField txt_u_sha256;
    private javax.swing.JTextField txt_u_sha512;
    // End of variables declaration//GEN-END:variables
}
